/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppUploadRouteImport } from './routes/_app.upload'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppPredictionsRouteImport } from './routes/_app.predictions'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppChatbotRouteImport } from './routes/_app.chatbot'
import { Route as AppAnomaliesRouteImport } from './routes/_app.anomalies'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPredictionsRoute = AppPredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatbotRoute = AppChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => AppRoute,
} as any)
const AppAnomaliesRoute = AppAnomaliesRouteImport.update({
  id: '/anomalies',
  path: '/anomalies',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anomalies': typeof AppAnomaliesRoute
  '/chatbot': typeof AppChatbotRoute
  '/dashboard': typeof AppDashboardRoute
  '/predictions': typeof AppPredictionsRoute
  '/reports': typeof AppReportsRoute
  '/upload': typeof AppUploadRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anomalies': typeof AppAnomaliesRoute
  '/chatbot': typeof AppChatbotRoute
  '/dashboard': typeof AppDashboardRoute
  '/predictions': typeof AppPredictionsRoute
  '/reports': typeof AppReportsRoute
  '/upload': typeof AppUploadRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/anomalies': typeof AppAnomaliesRoute
  '/_app/chatbot': typeof AppChatbotRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/predictions': typeof AppPredictionsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/upload': typeof AppUploadRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anomalies'
    | '/chatbot'
    | '/dashboard'
    | '/predictions'
    | '/reports'
    | '/upload'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anomalies'
    | '/chatbot'
    | '/dashboard'
    | '/predictions'
    | '/reports'
    | '/upload'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/anomalies'
    | '/_app/chatbot'
    | '/_app/dashboard'
    | '/_app/predictions'
    | '/_app/reports'
    | '/_app/upload'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/upload': {
      id: '/_app/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/predictions': {
      id: '/_app/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof AppPredictionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chatbot': {
      id: '/_app/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof AppChatbotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/anomalies': {
      id: '/_app/anomalies'
      path: '/anomalies'
      fullPath: '/anomalies'
      preLoaderRoute: typeof AppAnomaliesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnomaliesRoute: typeof AppAnomaliesRoute
  AppChatbotRoute: typeof AppChatbotRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPredictionsRoute: typeof AppPredictionsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppUploadRoute: typeof AppUploadRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnomaliesRoute: AppAnomaliesRoute,
  AppChatbotRoute: AppChatbotRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPredictionsRoute: AppPredictionsRoute,
  AppReportsRoute: AppReportsRoute,
  AppUploadRoute: AppUploadRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
